DROP TABLE IF EXISTS satuan;
CREATE TABLE satuan (
    satuan VARCHAR(10) PRIMARY KEY,
    name VARCHAR(50)
);
TRUNCATE TABLE satuan;
INSERT INTO satuan (satuan, name) VALUES
('Bdl','Bendel'),
('Bh','Buah'),
('Bks','Bungkus'),
('Box','Box'),
('Btl','Botol'),
('Can','Can'),
('Con','Cone'),
('Drm','Drum'),
('Dus','Kardus'),
('Gln','Gallon'),
('Grm','Gram'),
('Grs','Gross'),
('Ikt','Ikat'),
('Jam','Jam'),
('Kbk','Kubik'),
('Kg','Kilogram'),
('Kdi','Kodi'),
('Ktn','Karton'),
('Kw','Kwintal'),
('Lbr','Lembar'),
('Ljr','Lonjor'),
('Lsn','Lusin'),
('Ltr','Liter'),
('Ml','Mililiter'),
('Mtr','Meter'),
('Ons','Ons'),
('Pak','Pak'),
('Pcs','Potong'),
('Pel','Pelayanan'),
('Pl','Pail'),
('Pon','Pon'),
('Prs','Porsi'),
('Psg','Pasang'),
('Rim','Rim'),
('Rol','Roll'),
('Sak','Sak'),
('Set','Set'),
('Tbg','Tabung'),
('Tmb','Timba'),
('Ton','Ton'),
('Tub','Tube'),
('Unt','Unit');